# Generated by Django 3.2.8 on 2021-11-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'grade_level',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travelpages.grade_level', to_field='class_level')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
